# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 20:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_choice_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='number',
        ),
    ]
